version: '3.1'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: recipes_api
      POSTGRES_PASSWORD: recipes_api_password
      POSTGRES_DATABASE: recipes
    ports:
      - 5432:5432